# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        db_user_provider:
          entity:
            class: AppBundle:User
            property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        doc:
            pattern: ^/doc
            anonymous: true
        main:
            anonymous: ~
            guard:
              authenticators:
                - AppBundle\Security\Authenticator
            stateless: true

    access_control:
      - { path: ^/posts, roles: ROLE_USER }